group: travis_latest
language: python
cache: pip
python:
    - 2.7
    - 3.6
install:
    - pip install --upgrade pip
    #- pip install pycocotools
    #- pip install git://github.com/cocodataset/cocoapi.git/PythonAPI
    #- pip install git://github.com/cocodataset/cocoapi.git
    #- pip install git+https://github.com/cocodataset/cocoapi/PythonAPI
    #- pip install git+https://github.com/cocodataset/cocoapi/PythonAPI
    - wget https://github.com/cocodataset/cocoapi/archive/master.zip -O pycocotools.zip
    - unzip pycocotools.zip
    - ls -Fla
    - rm pycocotools.zip
    - cd pycocotools/PythonAPI ; make install ; cd
script:
    - true
